package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	if len(os.Args) != 3 {
		_, _ = fmt.Fprintln(os.Stderr, "usage: embedopenapi <input.json> <output.go>")
		os.Exit(2)
	}

	input, output := os.Args[1], os.Args[2]
	raw, err := os.ReadFile(input)
	if err != nil {
		panic(err)
	}

	var compact bytes.Buffer
	if err := json.Compact(&compact, raw); err != nil {
		panic(err)
	}

	source := []byte(`// Code generated by internal/tools/embedopenapi; DO NOT EDIT.
package openapi

const PublicV1JSON = ` + strconv.Quote(compact.String()) + "\n")

	formatted, err := format.Source(source)
	if err != nil {
		panic(err)
	}

	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(output, formatted, 0644); err != nil {
		panic(err)
	}
}
